import test from "node:test";
import assert from "node:assert/strict";
import { makeComputeEconomy } from "../sidecar/governance/compute-economy.mjs";

test("Compute Economy approves bounded compute and records usage",()=>{const e=makeComputeEconomy({budgets:{missionCents:20,workerCents:15,taskCents:10},providerStatuses:{apinex:"available"}});const a=e.authorize({missionId:"m",workerId:"w",taskId:"t",provider:"apinex",model:"free/gpt-5.6-luna"});assert.equal(a.approved,true);const u=e.recordUsage({authorization:a,inputTokens:100,outputTokens:50,actualCost:0});assert.equal(u.actualCost,0);assert.equal(e.report({missionId:"m"}).requestCount,1);});
test("Compute Economy rejects unavailable or rate-limited providers",()=>{const e=makeComputeEconomy({providerStatuses:{apinex:"rate-limited"}});assert.throws(()=>e.authorize({missionId:"m",workerId:"w",taskId:"t",provider:"apinex",model:"free/gpt-5.6-luna"}),/rate-limited/);});
test("Compute Economy fails closed when a task budget would be exceeded",()=>{const e=makeComputeEconomy({budgets:{missionCents:100,workerCents:100,taskCents:1}});assert.throws(()=>e.authorize({missionId:"m",workerId:"w",taskId:"t",provider:"apinex",model:"paid-model",estimatedCost:.02}),/budget exceeded/);});

test("Compute Economy allocates the cheapest approved model through the governed router",async()=>{const calls=[];const e=makeComputeEconomy({budgets:{missionCents:100,workerCents:100,taskCents:100},providerStatuses:{apinex:"available",openrouter:"available"},router:{resolve:async r=>{calls.push(r);return{allowed:true,...r,source:"starforge-governed-model-router"};}}});const a=await e.allocate({missionId:"m",workerId:"w",taskId:"t",candidates:[{provider:"openrouter",model:"paid",estimatedCost:.04,quality:10},{provider:"apinex",model:"free/gpt-5.6-luna",estimatedCost:0,quality:1}]});assert.equal(a.provider,"apinex");assert.equal(a.model,"free/gpt-5.6-luna");assert.equal(calls.length,2);});
test("Compute Economy reservation settles usage and records ROI",async()=>{const e=makeComputeEconomy({budgets:{missionCents:100,workerCents:100,taskCents:100},providerStatuses:{apinex:"available"},router:{resolve:async r=>({allowed:true,...r})}});const r=await e.requestCompute({missionId:"m",workerId:"w",taskId:"t",provider:"apinex",model:"free/gpt-5.6-luna",estimatedCost:0,reason:"cheap inference"});assert.equal(r.status,undefined);const s=e.settleCompute(r.reservationId,{actualCost:0,usage:{inputTokens:120,outputTokens:40},revenueUsd:14.2,outcome:"completed"});assert.equal(s.entry.actualCost,0);assert.equal(e.report({missionId:"m"}).revenueUsd,14.2);});
test("Compute Economy fails closed when every candidate is rejected",async()=>{const e=makeComputeEconomy({providerStatuses:{apinex:"available",openrouter:"unavailable"},router:{resolve:async()=>{throw new Error("rejected");}}});await assert.rejects(()=>e.requestCompute({missionId:"m",workerId:"w",taskId:"t",candidates:[{provider:"apinex",model:"free/a",estimatedCost:0},{provider:"openrouter",model:"free/b",estimatedCost:0}]}),/failed closed/);});
test("Compute Economy refuses settlement above the reservation ceiling",async()=>{const e=makeComputeEconomy({budgets:{missionCents:100,workerCents:100,taskCents:100},providerStatuses:{apinex:"available"},router:{resolve:async r=>({allowed:true,...r})}});const r=await e.requestCompute({missionId:"m",workerId:"w",taskId:"t",provider:"apinex",model:"paid",estimatedCost:.05});assert.throws(()=>e.settleCompute(r.reservationId,{actualCost:.06}),/reserved hard ceiling/);});
