// StarForge Compute Economy: budgeted, fail-closed compute admission above the existing model router.
const COMPLEXITY_RANK = Object.freeze({ simple: 1, normal: 2, complex: 3, critical: 4 });
const money = (v) => { const n = Number(v); return Number.isFinite(n) && n >= 0 ? n : 0; };
const clone = (v) => structuredClone(v);
function normalizeCandidate(c) { const provider=String(c?.provider??"").trim().toLowerCase(), model=String(c?.model??"").trim(); if(!provider||!model) throw new Error("compute candidate requires provider and model"); const estimatedCost=money(c?.estimatedCost); return {...c,provider,model,estimatedCost,free:c?.free===true||estimatedCost===0,capability:Math.max(1,Math.min(4,Number(c?.capability??2)||2))}; }
export function makeComputeEconomy({router=null,policy={}}={}) {
 const state={budgets:new Map(),reservations:new Map(),ledger:[],sequence:0}; const currency=String(policy.currency??"EUR").toUpperCase();
 function setBudget(scope,id,amount,{hard=true}={}) { if(!id||!["mission","worker","task"].includes(scope)) throw new Error("invalid compute budget"); const e={scope,id:String(id),budget:money(amount),hard:hard!==false}; state.budgets.set(scope+":"+id,e); return clone(e); }
 function budgetFor(scope,id){return state.budgets.get(scope+":"+id)??null;}
 function spentFor(scope,id){return state.ledger.filter(e=>e.status==="settled"&&e[scope+"Id"]===String(id)).reduce((s,e)=>s+money(e.actualCost),0);}
 function reservedFor(scope,id){return [...state.reservations.values()].filter(e=>e.status==="reserved"&&e[scope+"Id"]===String(id)).reduce((s,e)=>s+money(e.reservedCost),0);}
 function check(scope,id,cost){const b=budgetFor(scope,id);if(!b)return{allowed:true,remaining:Infinity,configured:false};const used=spentFor(scope,id)+reservedFor(scope,id),remaining=Math.max(0,b.budget-used);return{allowed:cost<=remaining+1e-12,remaining,configured:true,budget:b.budget,used};}
 async function requestCompute({missionId,workerId,taskId,complexity="normal",candidates=[],provider="",model="",estimatedCost=null,reason=""}={}) {
  const rank=COMPLEXITY_RANK[String(complexity).toLowerCase()]??2; let pool=Array.isArray(candidates)?candidates.map(normalizeCandidate):[];
  if(!pool.length&&provider&&model)pool=[normalizeCandidate({provider,model,estimatedCost:estimatedCost??0,capability:rank})]; if(!pool.length)throw new Error("compute economy has no approved compute candidates");
  pool=pool.filter(c=>c.capability>=rank).sort((a,b)=>a.estimatedCost-b.estimatedCost||a.capability-b.capability||a.provider.localeCompare(b.provider)||a.model.localeCompare(b.model)); if(!pool.length)throw new Error("compute economy has no candidate capable of the requested complexity");
  let selected=null,lastError=null; for(const c of pool){try{const route=router?.resolve?await router.resolve({provider:c.provider,model:c.model}):{allowed:true,provider:c.provider,model:c.model,free:c.free,source:"compute-economy-policy"};if(!route?.allowed)throw new Error("model router did not approve compute candidate");selected={...c,route};break;}catch(e){lastError=e;}}
  if(!selected)throw new Error("compute economy failed closed: no approved provider/model can satisfy the request"+(lastError?": "+lastError.message:""));
  for(const [scope,id] of [["mission",missionId],["worker",workerId],["task",taskId]])if(id&&!check(scope,id,selected.estimatedCost).allowed)throw new Error("compute budget exceeded for "+scope+": "+id);
  const reservationId="compute-"+(++state.sequence),reservation={reservationId,missionId:missionId?String(missionId):null,workerId:workerId?String(workerId):null,taskId:taskId?String(taskId):null,complexity:String(complexity),reason:String(reason),provider:selected.provider,model:selected.model,reservedCost:selected.estimatedCost,currency,status:"reserved",route:clone(selected.route),createdAt:new Date().toISOString()}; state.reservations.set(reservationId,reservation);state.ledger.push(clone(reservation));return clone(reservation);
 }
 function settleCompute(id,{actualCost=null,usage={},status="settled",outcome=""}={}){const r=state.reservations.get(String(id));if(!r)throw new Error("unknown compute reservation");if(r.status!=="reserved")throw new Error("compute reservation is already closed");const actual=actualCost==null?r.reservedCost:money(actualCost);if(actual>r.reservedCost+1e-12)throw new Error("compute settlement exceeds the reserved hard ceiling");r.status=status;r.actualCost=actual;r.usage=clone(usage||{});r.outcome=String(outcome);r.settledAt=new Date().toISOString();state.reservations.set(r.reservationId,r);const i=state.ledger.findIndex(e=>e.reservationId===r.reservationId&&e.status==="reserved");if(i>=0)state.ledger[i]=clone(r);return clone(r);}
 function releaseCompute(id,reason="released"){const r=state.reservations.get(String(id));if(!r)throw new Error("unknown compute reservation");if(r.status!=="reserved")return clone(r);r.status="released";r.actualCost=0;r.outcome=String(reason);r.releasedAt=new Date().toISOString();state.reservations.set(r.reservationId,r);const i=state.ledger.findIndex(e=>e.reservationId===r.reservationId&&e.status==="reserved");if(i>=0)state.ledger[i]=clone(r);return clone(r);}
 function snapshot(){return clone({currency,budgets:[...state.budgets.values()],reservations:[...state.reservations.values()],ledger:state.ledger});}
 return Object.freeze({setBudget,budgetFor,requestCompute,settleCompute,releaseCompute,snapshot,spentFor,reservedFor});
}
export {COMPLEXITY_RANK};
