'use strict';
// Economic campaign ceiling: LVL 100 = €10M net operating capital. The live finance bridge supplies the actual governed balance.
(function(){
  if(typeof document==='undefined'||typeof StationUI==='undefined'||!StationUI.registerWindow)return;
  const esc=StationUI.h.esc;
  const MILESTONES=Object.freeze([[1,0],[5,1000],[10,5000],[20,25000],[30,75000],[40,200000],[50,500000],[60,1000000],[70,2000000],[80,3500000],[90,6000000],[99,9000000],[100,10000000]]);
  function levelForCapital(capital){const n=Number(capital);if(!Number.isFinite(n)||n<0)return null;let level=1;for(const [candidate,threshold] of MILESTONES){if(n>=threshold)level=candidate;else break;}return Math.min(100,level);}
  function nextMilestone(level){return MILESTONES.find(([candidate])=>candidate>level)||null;}
  function statusForAgent(agent){const id=String(agent&&(agent.id||agent.agentId)||'');let running=false;try{running=!!(StationUI.isAgentRunning&&StationUI.isAgentRunning(id));}catch(_){}return running?['WORKING','working']:['IDLE','idle'];}
  function render(body){
    body.innerHTML='';const root=document.createElement('section');root.className='sf-hq';
    root.innerHTML='<div class="sf-hq-head"><div><div class="sf-kicker">STARFORGE HQ</div><h2>COMPANY COMMAND ROOM</h2><p>StarNet workforce · governed by StarForge</p><button type="button" class="sf-room-launch" data-open-worker-room>▣ OPEN STARFORGE WORKER ROOM</button></div><div class="sf-link-state" role="status"><span data-connection-label>STARFORGE LINK · TEST BRIDGE</span><small data-connection-source>checking source…</small></div></div><article class="sf-capital"><div class="sf-section-label">COMPANY LEVEL</div><div class="sf-level-line"><strong class="sf-level">LVL —</strong><span class="sf-tier" data-tier>RANK —</span><span class="sf-capital-value">CAPITAL FEED PENDING</span></div><div class="sf-meter"><i></i></div><div class="sf-next">Finance bridge not connected — no balance is invented.</div><div class="sf-level-detail" data-level-detail>GROWTH OPERATIONS</div><div class="sf-unlocks" data-unlocks></div></article><div class="sf-leadership"></div><section class="sf-mission"><div class="sf-section-label">MISSION CONTROL</div><div class="sf-mission-title" data-mission="title">MISSION NOT SET</div><div class="sf-mission-objective" data-mission="objective">No company objective recorded.</div><div class="sf-objective-progress" data-mission="objective-progress">OBJECTIVE PROGRESS PENDING</div><div class="sf-projects" data-mission="projects"></div><div class="sf-activity" data-mission="activity"></div></section><section class="sf-execution"><div class="sf-section-label">STARFORGE EXECUTION FEED</div><div class="sf-execution-stats"><span>IN PROGRESS <b data-sf="in-progress">—</b></span><span>COMPLETED <b data-sf="completed">—</b></span><span>FAILED <b data-sf="failed">—</b></span><span>BLOCKED <b data-sf="blocked">—</b></span><span>COMPANY XP <b data-sf="company-xp">—</b></span><span>XP SOURCE <b data-sf="company-xp-source">—</b></span><span>MISSION LEVEL <b data-sf="company-xp-level">—</b></span><span>XP TO NEXT <b data-sf="company-xp-next">—</b></span><span>MISSION RANK <b data-sf="mission-rank">—</b></span><span>NEXT UNLOCK <b data-sf="mission-unlock">—</b></span></div><div class="sf-recent"></div></section><section class="sf-finance"><div class="sf-section-label">FINANCE TELEMETRY</div><div class="sf-finance-grid"><span>CASH <b data-fin="cash">—</b></span><span>TAX RESERVE <b data-fin="tax">—</b></span><span>LIABILITIES <b data-fin="liabilities">—</b></span><span>LEDGER ENTRIES <b data-fin="entries">—</b></span></div><div class="sf-ledger"></div></section><section class="sf-roster"><div class="sf-section-label">STARNET WORKFORCE</div><div class="sf-roster-meta"></div><div class="sf-workers"></div></section>';
    const roomLaunch=root.querySelector('[data-open-worker-room]'); if(roomLaunch) roomLaunch.addEventListener('click',()=>{if(StationUI.h&&typeof StationUI.h.openTerm==='function') StationUI.h.openTerm('starforge-worker-room');});
    const leaders=root.querySelector('.sf-leadership');[['CHO','HUMAN OWNER'],['PA','OVERSIGHT'],['CEO','OPERATIONS'],['VICE CEO','STARNET LEAD']].forEach(([n,r])=>{const c=document.createElement('div');c.className='sf-leader';c.innerHTML='<b>'+esc(n)+'</b><span>'+esc(r)+'</span>';leaders.appendChild(c);});
    const meta=root.querySelector('.sf-roster-meta'),workers=root.querySelector('.sf-workers');
    const executionStats={}; root.querySelectorAll('[data-sf]').forEach(el=>executionStats[el.dataset.sf]=el); const recentEl=root.querySelector('.sf-recent'); const financeStats={}; root.querySelectorAll('[data-fin]').forEach(el=>financeStats[el.dataset.fin]=el); const ledgerEl=root.querySelector('.sf-ledger');
    const levelEl=root.querySelector('.sf-level'),tierEl=root.querySelector('[data-tier]'),capitalEl=root.querySelector('.sf-capital-value'),meterEl=root.querySelector('.sf-meter i'),nextEl=root.querySelector('.sf-next');
    const missionTitle=root.querySelector('[data-mission="title"]'),missionObjective=root.querySelector('[data-mission="objective"]'),projectsEl=root.querySelector('[data-mission="projects"]'),activityEl=root.querySelector('[data-mission="activity"]'); const connectionLabel=root.querySelector('[data-connection-label]'),connectionSource=root.querySelector('[data-connection-source]');
    const money=(amount,currency='EUR')=>{const n=Number(amount);return Number.isFinite(n)?new Intl.NumberFormat('en-IE',{style:'currency',currency:String(currency).toUpperCase(),maximumFractionDigits:0}).format(n):'—';};
    async function refreshGovernance(){
      try{
        const response=await fetch('/api/starforge/governance',{cache:'no-store'});
        if(!response.ok) throw new Error('governance feed unavailable');
        const data=await response.json();
        const company=data&&data.company; const connection=data&&data.connection; if(connection){const live=connection.runtimeMode==='live-starnet'; connectionLabel.textContent=live?'STARFORGE LINK · LIVE STARNET':'STARFORGE LINK · TEST BRIDGE'; connectionSource.textContent=String(connection.workforceSource||'workforce source unavailable');}
        const projects=Array.isArray(company?.projects)?company.projects:[];
        missionTitle.textContent=String(company?.mission||'MISSION NOT SET');
        missionObjective.textContent=String(company?.objective||'No company objective recorded.');
        projectsEl.replaceChildren();
        if(!projects.length){projectsEl.textContent='No governed projects recorded yet.';}
        else projects.slice(-5).reverse().forEach(project=>{const row=document.createElement('div');row.className='sf-project';row.innerHTML='<b>'+esc(project.title||'Untitled project')+'</b><span>'+esc(String(project.status||'unknown').toUpperCase())+'</span>';projectsEl.appendChild(row);});
        const objectiveProgress=Array.isArray(data?.gameplay?.objectiveProgress)?data.gameplay.objectiveProgress:[];
        const objectiveProgressEl=root.querySelector('[data-mission="objective-progress"]');
        if(objectiveProgressEl){const current=objectiveProgress[objectiveProgress.length-1];objectiveProgressEl.textContent=current?String(current.progressPercent??0)+'% · '+String(current.completed??0)+'/'+String(current.taskCount??0)+' TASKS DONE · '+String(current.companyXp??0)+' XP · '+String(current.assignedWorkerCount??0)+' WORKERS · '+String(current.outcome||'pending').toUpperCase():'OBJECTIVE PROGRESS PENDING';}
        const gameplayProjects=Array.isArray(data?.gameplay?.projects)?data.gameplay.projects:[];
        if(gameplayProjects.length){projectsEl.replaceChildren();gameplayProjects.slice(-5).reverse().forEach(project=>{const row=document.createElement('div');row.className='sf-project';row.innerHTML='<b>'+esc(project.title||'Untitled project')+'</b><span>'+esc(String(project.status||'unknown').toUpperCase())+' · '+esc(String(project.progressPercent??0))+'% · '+esc(String(project.completed??0))+'/'+esc(String(project.taskCount??0))+' DONE · '+esc(String(project.assignedWorkerCount??0))+' WORKERS · '+esc(String(project.outcome||'pending').toUpperCase())+'</span>';projectsEl.appendChild(row);}}
        const activity=Array.isArray(data?.gameplay?.activity)?data.gameplay.activity:[];
        if(activityEl){activityEl.replaceChildren();if(!activity.length){activityEl.textContent='No governed mission activity recorded yet.';}else{const label=document.createElement('div');label.className='sf-section-label';label.textContent='MISSION ACTIVITY';activityEl.appendChild(label);activity.slice(0,5).forEach(item=>{const row=document.createElement('div');row.className='sf-activity-row';row.innerHTML='<b>'+esc(item.title||'Untitled task')+'</b><span>'+esc(String(item.outcome||'pending').toUpperCase())+' · XP '+(Number(item.xpDelta)>0?'+':'')+esc(String(item.xpDelta??0))+' · '+esc(item.assigneeId||'unassigned')+(item.projectTitle?' · '+esc(item.projectTitle):'')+'</span>';activityEl.appendChild(row);});}}
        const capital=data&&data.capital;
        const execution=data&&data.execution;
        if(capital){ financeStats.cash.textContent=money(capital.availableCash,capital.currency); financeStats.tax.textContent=money(capital.taxReserve,capital.currency); financeStats.liabilities.textContent=money(capital.liabilities,capital.currency); financeStats.entries.textContent=String(capital.entryCount ?? 0); }
        const entries=Array.isArray(data?.finance?.recentEntries)?data.finance.recentEntries:[]; ledgerEl.replaceChildren(); if(!entries.length){ledgerEl.textContent='No finance ledger entries recorded yet.';} else entries.forEach(entry=>{const row=document.createElement('div');row.className='sf-ledger-row';row.innerHTML='<b>'+esc(String(entry.kind||'entry').replaceAll('-',' ').toUpperCase())+'</b><span>'+money(entry.amount,entry.currency)+'</span>';ledgerEl.appendChild(row);});
        for(const key of ['in-progress','completed','failed','blocked']) executionStats[key].textContent=Number(execution?.[{ 'in-progress':'inProgress', completed:'completed', failed:'failed', blocked:'blocked' }[key]] ?? 0);
        executionStats['company-xp'].textContent=String(Number(data?.gameplay?.companyXp??0))+' XP'; executionStats['company-xp-source'].textContent=String(data?.gameplay?.companyXpSource||'unavailable'); const xpProgress=data?.gameplay?.companyXpProgress; if(executionStats['company-xp-level']) executionStats['company-xp-level'].textContent=xpProgress?'LVL '+String(xpProgress.gameplayLevel):'—'; if(executionStats['company-xp-next']) executionStats['company-xp-next'].textContent=xpProgress?String(xpProgress.remainingToNext)+' XP':'—'; const missionRankEl=root.querySelector('[data-sf="mission-rank"]'); const missionUnlockEl=root.querySelector('[data-sf="mission-unlock"]'); if(missionRankEl) missionRankEl.textContent=xpProgress?String(xpProgress.missionRank||'INITIATE'):'—'; if(missionUnlockEl) missionUnlockEl.textContent=xpProgress?.nextMilestone?String(xpProgress.nextMilestone.name)+' · '+String(xpProgress.nextMilestone.remainingToNext)+' XP':'MAX MISSION RANK';
        const recent=Array.isArray(execution?.recentTasks)?execution.recentTasks.slice().reverse():[];
        recentEl.replaceChildren();
        if(!recent.length){recentEl.textContent='No governed StarNet tasks recorded yet.';} else recent.slice(0,5).forEach(task=>{const row=document.createElement('div');row.className='sf-task';row.innerHTML='<b>'+esc(task.title||'Untitled task')+'</b><span>'+esc(String(task.status||'unknown').toUpperCase())+' · '+esc(task.assigneeId||'unassigned')+'</span>';recentEl.appendChild(row);});
        if(!capital || capital.source!=='starforge-governed-company-ledger') throw new Error('governed finance source unavailable');
        const net=Number(capital.netOperatingCapital);
        const levelFeed=data?.level;
        if(!levelFeed || levelFeed.source!=='starforge-governed-company-ledger') throw new Error('authoritative company level unavailable');
        if(Number(levelFeed.currentCapital)!==net) throw new Error('company level capital does not match governed capital');
        const tier=String(levelFeed.rank||'STARTUP');
        levelEl.textContent='LVL '+String(levelFeed.level); tierEl.textContent='RANK · '+tier;
        capitalEl.textContent=new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(net)+' NET OPERATING CAPITAL';
        meterEl.style.width=Math.max(0,Math.min(100,Number(levelFeed.progressPercent)||0))+'%';
        const progress=Number(levelFeed.progressPercent)||0;
        const detail=root.querySelector('[data-level-detail]');
        const unlocks=root.querySelector('[data-unlocks]');
        detail.textContent=levelFeed.nextLevel
          ? 'LEVEL '+String(levelFeed.level)+' · '+progress.toFixed(1)+'% THROUGH CURRENT LEVEL'
          : 'LEVEL 100 · LEGENDARY STATUS';
        const governedUnlocks=Array.isArray(levelFeed.unlocks)?levelFeed.unlocks:[];
        unlocks.replaceChildren();
        governedUnlocks.slice(-3).reverse().forEach(unlock=>{
          const row=document.createElement('span');row.className='sf-unlock';row.textContent='✓ LVL '+String(unlock.level)+' · '+String(unlock.name);unlocks.appendChild(row);
        });
        nextEl.textContent=levelFeed.nextLevel
          ? 'NEXT LEVEL · '+new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(levelFeed.nextThreshold)+' · '+new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(levelFeed.remainingToNext)+' TO GO'
          : 'MAX LEVEL · €10,000,000+';
      }catch(_){ connectionLabel.textContent='STARFORGE LINK · TEST BRIDGE'; connectionSource.textContent='governance feed unavailable'; levelEl.textContent='LVL —'; tierEl.textContent='RANK —'; capitalEl.textContent='CAPITAL FEED PENDING'; meterEl.style.width='0'; nextEl.textContent='Finance bridge unavailable — no balance is invented.'; }
    }
    refreshGovernance();
    function paint(governance){const governed=Array.isArray(governance?.workforce?.workers)?governance.workforce.workers:[];const stationAgents=Array.isArray(StationUI.present)?StationUI.present:[];const live=governed.map(worker=>{const station=stationAgents.find(agent=>String(agent.id||agent.agentId)===String(worker.id));let stationRunning=false;try{stationRunning=!!(StationUI.isAgentRunning&&StationUI.isAgentRunning(String(worker.id)));}catch(_){}const runtimeStatus=stationRunning?'working':(worker.status==='working'?'working':'idle');return {agent:{...worker,...(station||{})},status:runtimeStatus==='working'?['WORKING','working']:['IDLE','idle'],activeRun:worker.activeRun||null,performance:worker.performance||null,station};});const working=live.filter(x=>x.status[1]==='working').length;meta.textContent=live.length+' WORKER'+(live.length===1?'':'S')+' · '+working+' WORKING · '+(live.length-working)+' IDLE';workers.replaceChildren();if(!live.length){const e=document.createElement('div');e.className='sf-empty';e.textContent='No StarNet workers are currently exposed by the governed workforce feed.';workers.appendChild(e);return;}for(const item of live){const a=item.agent,c=document.createElement('button');c.type='button';c.className='sf-worker';c.title=item.station?'Open StarNet agent dossier':'StarNet worker — dossier unavailable in this UI session';const run=item.activeRun;const activity=run?.title||run?.task||run?.label||'';const performance=item.performance||{};const reliability=Number.isFinite(Number(performance?.reliabilityPercent))?String(performance.reliabilityPercent)+'% RELIABILITY':(Number(performance.taskCount)>0?'NO RESOLVED TASKS':'NO TASK HISTORY');c.innerHTML='<div class="sf-avatar">◆</div><div class="sf-worker-main"><b>'+esc(a.name||a.id||'Unnamed worker')+'</b><span>'+esc(a.role||'StarNet agent')+' · '+esc(a.model||'model unavailable')+(a.provider?' · '+esc(a.provider):'')+(activity?' · '+esc(activity):'')+'</span><small class="sf-worker-stats">'+esc(String(performance.completed??0))+' DONE · '+esc(String(performance.failed??0))+' FAILED · '+esc(reliability)+'</small></div><span class="sf-status '+item.status[1]+'">'+item.status[0]+'</span><span class="sf-open">'+(item.station?'OPEN ›':'LINK PENDING')+'</span>';c.addEventListener('click',()=>{if(!item.station)return;const agents=Array.isArray(StationUI.present)?StationUI.present:[];const index=agents.findIndex(x=>String(x.id||x.agentId)===String(a.id||a.agentId));if(index>=0&&typeof StationUI.openAgent==='function')StationUI.openAgent(index);});workers.appendChild(c);}}
    paint();let latestGovernance=null;const refreshWorkforce=async()=>{try{const response=await fetch('/api/starforge/governance',{cache:'no-store'});if(response.ok){latestGovernance=await response.json();paint(latestGovernance);}}catch(_){}};refreshWorkforce();const timer=window.setInterval(()=>{if(root.isConnected){paint(latestGovernance);refreshWorkforce();}else window.clearInterval(timer);},1000);body.appendChild(root);
  }
  StationUI.registerWindow('starforge-hq','STARFORGE HQ',render,{console:true,className:'starforge-hq-win'});
  window.StarForgeHQ=Object.freeze({levelForCapital,nextMilestone,milestones:MILESTONES});
})();
